### ISSUE TITLE
Timeout Error

### ISSUE THREAD

**Issue by vibhuyadav** [davecardwell/publix-coupon-clipper#12]
I am getting a timeout error. Any idea what could be wrong?
`..[vyadav@VYADAV-LT] - [~/publix-coupon-clipper] - [Tue Mar 02, 12:20]
..[$] <( (git)-[master]-)> npx publix-coupon-clipper vib.yad@gmail.com my_password_is_hidden
Downloading Chromium r818858 - 132.4 Mb [====================] 100% 0.0s
Setting up page
Logging in to Publix.com
New document request: GET https://www.publix.com/savings/digital-coupons?sort=Newest
New document request: GET https://www.publix.com/login?redirectUrl=/savings/digital-coupons?sort=Newest
New document request: GET https://account.publix.com/......./b2c_1a_publixsigninmigration_signin/oauth2/v2.0/authorize.........
{ TimeoutError: waiting for selector `.error` failed: timeout 30000ms exceeded
    at new WaitTask (/Users/vyadav/.npm/_npx/36392/lib/node_modules/publix-coupon-clipper/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:505:34)
    at DOMWorld.waitForSelectorInPage (/Users/vyadav/.npm/_npx/36392/lib/node_modules/publix-coupon-clipper/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:416:26)
    at Object.internalHandler.waitFor (/Users/vyadav/.npm/_npx/36392/lib/node_modules/publix-coupon-clipper/node_modules/puppeteer/lib/cjs/puppeteer/common/QueryHandler.js:31:77)
    at DOMWorld.waitForSelector (/Users/vyadav/.npm/_npx/36392/lib/node_modules/publix-coupon-clipper/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:312:29)
    at Frame.waitForSelector (/Users/vyadav/.npm/_npx/36392/lib/node_modules/publix-coupon-clipper/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:842:51)
    at Page.waitForSelector (/Users/vyadav/.npm/_npx/36392/lib/node_modules/publix-coupon-clipper/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1285:33)
    at Promise.all.Promise (/Users/vyadav/.npm/_npx/36392/lib/node_modules/publix-coupon-clipper/dist/index.node.js:171:10)
    at new Promise (<anonymous>)
    at logInToPublix (/Users/vyadav/.npm/_npx/36392/lib/node_modules/publix-coupon-clipper/dist/index.node.js:159:22)
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'TimeoutError' }`

**Comment by davecardwell** [comment]
Thank you for the report, @vibhuyadav.

It looks like Publix have changed something about their login process so I will have to investigate and see if I can adapt publix-coupon-clipper. I don’t have an ETA at this time but will update this issue as I know more.

**Comment by davecardwell** [comment]
This no longer seems to be an issue and publix-coupon-clipper runs fine for me again.

**Comment by vibhuyadav** [comment]
> This no longer seems to be an issue and publix-coupon-clipper runs fine for me again.

Yes. Can confirm this is no longer the same issue. I see a new one
```
TimeoutError: waiting for selector `.error` failed: timeout 30000ms exceeded
    at new WaitTask (/Users/vibhuyadav/.npm/_npx/f4140283e38a4f6c/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:509:34)
    at DOMWorld.waitForSelectorInPage (/Users/vibhuyadav/.npm/_npx/f4140283e38a4f6c/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:420:26)
    at Object.internalHandler.waitFor (/Users/vibhuyadav/.npm/_npx/f4140283e38a4f6c/node_modules/puppeteer/lib/cjs/puppeteer/common/QueryHandler.js:31:77)
    at DOMWorld.waitForSelector (/Users/vibhuyadav/.npm/_npx/f4140283e38a4f6c/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:313:29)
    at Frame.waitForSelector (/Users/vibhuyadav/.npm/_npx/f4140283e38a4f6c/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:841:51)
    at Page.waitForSelector (/Users/vibhuyadav/.npm/_npx/f4140283e38a4f6c/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1333:33)
    at /Users/vibhuyadav/.npm/_npx/f4140283e38a4f6c/node_modules/publix-coupon-clipper/dist/index.node.js:171:10
    at new Promise (<anonymous>)
    at logInToPublix (/Users/vibhuyadav/.npm/_npx/f4140283e38a4f6c/node_modules/publix-coupon-clipper/dist/index.node.js:159:22)```
