### ISSUE TITLE
Broken on updated publix site?

### ISSUE THREAD

**Issue by diego898** [davecardwell/publix-coupon-clipper#23]
just reporting back that I think the publix site has updated and now this returns:

```
New document request: GET https://www.publix.com/savings/digital-coupons?sort=Newest
Error: No node found for selector: a.sign-in-button
    at Object.assert (/Users/diego/.npm/_npx/f4140283e38a4f6c/node_modules/puppeteer/lib/cjs/puppeteer/common/assert.js:26:15)
    at DOMWorld.click (/Users/diego/.npm/_npx/f4140283e38a4f6c/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:277:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 2)
    at async logInToPublix (/Users/diego/.npm/_npx/f4140283e38a4f6c/node_modules/publix-coupon-clipper/dist/index.node.js:142:3)
    at async clipCoupons (/Users/diego/.npm/_npx/f4140283e38a4f6c/node_modules/publix-coupon-clipper/dist/index.node.js:60:5)
    at async main (/Users/diego/.npm/_npx/f4140283e38a4f6c/node_modules/publix-coupon-clipper/dist/index.node.js:268:3)
    at async /Users/diego/.npm/_npx/f4140283e38a4f6c/node_modules/publix-coupon-clipper/dist/index.node.js:24:7
```

**Comment by vibhuyadav** [comment]
I am getting the same error. I guess publix updated their website. It would nice for them to give a coupon clipper API :D
