### ISSUE TITLE
Clueless clipper

### ISSUE THREAD

**Issue by konzatech** [davecardwell/publix-coupon-clipper#4]
I absolutely love this response to making us "clip" electronic coupons. I'm a semi-retired Solaris and Linux systems admin, but not a skilled javascript developer. When I try to use your tool, I get the following. I am clueless and would appreciate any help getting your coupon clipper to work. Other than redacting my Publix password, this is the output I get. I'm running this on Linux Mint.

Thanks!

$ npx publix-coupon-clipper jeff.hanck@gmail.com ************
Downloading Chromium r722234 - 121.1 Mb [====================] 100% 0.0s 
(node:30284) UnhandledPromiseRejectionWarning: ReferenceError: URL is not defined
    at Page.filterRequests (/home/jeff/.npm/_npx/30284/lib/node_modules/publix-coupon-clipper/dist/index.node.js:85:15)
    at emitOne (events.js:116:13)
    at Page.emit (events.js:211:7)
    at NetworkManager.Page.networkManager.on.event (/home/jeff/.npm/_npx/30284/lib/node_modules/publix-coupon-clipper/node_modules/puppeteer/lib/Page.js:110:68)
    at emitOne (events.js:121:20)
    at NetworkManager.emit (events.js:211:7)
    at NetworkManager._onRequest (/home/jeff/.npm/_npx/30284/lib/node_modules/publix-coupon-clipper/node_modules/puppeteer/lib/NetworkManager.js:234:10)
    at NetworkManager._onRequestPaused (/home/jeff/.npm/_npx/30284/lib/node_modules/publix-coupon-clipper/node_modules/puppeteer/lib/NetworkManager.js:210:12)
    at emitOne (events.js:116:13)
    at CDPSession.emit (events.js:211:7)
(node:30284) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:30284) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
{ TimeoutError: Navigation timeout of 30000 ms exceeded
    at Promise.then (/home/jeff/.npm/_npx/30284/lib/node_modules/publix-coupon-clipper/node_modules/puppeteer/lib/LifecycleWatcher.js:142:21)
    at <anonymous>
  -- ASYNC --
    at Frame.<anonymous> (/home/jeff/.npm/_npx/30284/lib/node_modules/publix-coupon-clipper/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.goto (/home/jeff/.npm/_npx/30284/lib/node_modules/publix-coupon-clipper/node_modules/puppeteer/lib/Page.js:672:49)
    at Page.<anonymous> (/home/jeff/.npm/_npx/30284/lib/node_modules/publix-coupon-clipper/node_modules/puppeteer/lib/helper.js:112:23)
    at logInToPublix (/home/jeff/.npm/_npx/30284/lib/node_modules/publix-coupon-clipper/dist/index.node.js:116:14)
    at clipCoupons (/home/jeff/.npm/_npx/30284/lib/node_modules/publix-coupon-clipper/dist/index.node.js:57:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) name: 'TimeoutError' }

**Comment by davecardwell** [comment]
Hi there! The error seems to be `ReferenceError: URL is not defined`.

Please could you let me know what version of node you’re running? (`node -v`)

From the “History” table under https://nodejs.org/api/url.html#url_the_whatwg_url_api it sounds like it was added to Node.js in v6.13.0 and v7.0.0 but only made globally available in v10.0.0 as I am using it.

**Comment by davecardwell** [comment]
That did seem to be the issue. I installed Node.js v8.16.0 and was able to reproduce the problem, so fixed it in https://github.com/davecardwell/publix-coupon-clipper/commit/6b990a69c65de1eb18c6f30edddb49825b85ff95.

I published v2.1.2 to npm so it should be available when you run `npx publix-coupon-clipper` once the release has worked its way through their systems.

**Comment by davecardwell** [comment]
Oh, and thanks for the report @konzatech!
