### ISSUE TITLE
No node found for selector

### ISSUE THREAD

**Issue by ceefus** [davecardwell/publix-coupon-clipper#8]
Coupon clipper was working for a long time but it now I get this error.  Any ideas?

New document request: POST https://www.publix.com/
Error: No node found for selector: #tmpUserNameInput
    at Object.exports.assert (C:\Users\***\AppData\Roaming\npm-cache\_npx\3452\node_modules\publix-coupon-clipper\node_modules\puppeteer\lib\cjs\puppeteer\common\assert.js:26:15)
    at DOMWorld.type (C:\Users\***\AppData\Roaming\npm-cache\_npx\3452\node_modules\publix-coupon-clipper\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:304:21)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async logInToPublix (C:\Users\***\AppData\Roaming\npm-cache\_npx\3452\node_modules\publix-coupon-clipper\dist\index.node.js:139:3)
    at async clipCoupons (C:\Users\***\AppData\Roaming\npm-cache\_npx\3452\node_modules\publix-coupon-clipper\dist\index.node.js:60:5)
    at async main (C:\Users\***\AppData\Roaming\npm-cache\_npx\3452\node_modules\publix-coupon-clipper\dist\index.node.js:243:3)
    at async C:\Users\***\AppData\Roaming\npm-cache\_npx\3452\node_modules\publix-coupon-clipper\dist\index.node.js:24:7

**Comment by davecardwell** [comment]
Thanks for the report. It looks like they’ve made some changes to the log in process.

I will take a look and will update here when the next release is available.

**Comment by davecardwell** [comment]
Fixed in 5b2a93d1f7c9bba7ae40a2e6d778011e7db1f875, released to npm as v3.1.1.
